version: "3"

services:
  app:
    container_name: my_react_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:80"
    command: ["nginx", "-g", "daemon off;"]
